### ISSUE TITLE
Static Hosting with S3

### ISSUE THREAD

**Issue by deybhayden** [sdelements/lets-chat-s3#1]
Hey there,

When using this plugin, should the bucket be enabled to do static hosting? If so, the URL my bucket has doesn't correlate to the plugin. The URL I get contains 'website':

**example.s3-website-us-east-1.amazonaws.com**

instead of 

**example.s3-us-east-1.amazonaws.com**

Am I missing something or should the plugin include 'website' when building the URL? Thanks!

**Comment by deybhayden** [comment]
Hey again,

I can make a separate issue if you want, but after deleting and rebuilding my containers, I now have a problem of the images uploading properly, but the image URL isn't displayed as an S3 link at all anymore and the page is trying to link to a locally hosted image. Let me know what settings (if any) you'd like to see.

**Comment by sibartlett** [comment]
You mean the URLs in the web interface? They are supposed to link to a local URL. The Let's Chat server will redirect the requests to S3.

**Comment by deybhayden** [comment]
Yup - I am. I suppose that's my issue then - the redirect isn't working? Maybe due to the original issue I reported?
